services:
  mongodb:
    image: mongo:7
    container_name: ai-code-assistant-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: ai_code_assistant
    volumes:
      - mongodb_data:/data/db
    command: ['--replSet', 'rs0', '--bind_ip_all']
    restart: unless-stopped
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      retries: 30

volumes:
  mongodb_data:
